name: Go Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./taiwanstay-back

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25' # 建議使用較新的 Go 版本

    - name: Install dependencies
      run: go mod download

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.55
        working-directory: ./taiwanstay-back
        args: --timeout=5m

    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build -v ./...
