name: Go Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'

    - name: Install dependencies
      run: go mod download

    - name: Check for un-tidied go.mod
      run: |
        go mod tidy
        git diff --exit-code

    - name: Lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.59.1
        args: --timeout=5m

    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build -v ./...
